Yorth/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),

]

YouthDiabetesHelp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
            path('admin/', admin.site.urls),
            path('', include('home.urls')),

            path('about/', include('about.urls')),
            path('contact/', include('contact.urls')),
            path('article/', include('article.urls')),
            path('donation/', include('donation.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from . import views

app_name = 'article'
urlpatterns = [
    path('article/<int:id>/', views.article_view, name='article'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),

]

Yorth/article/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Article(models.Model):
    title = models.CharField(max_length=200, verbose_name="عنوان")
    image = models.ImageField(upload_to="image/article", verbose_name="تصویر", help_text= "لطفاً تصویری با ابعاد 1921 در 966  پیکسل وارد کنید",)
    content = RichTextField(verbose_name="محتوا")
    public = models.DateField(verbose_name='تاربخ', auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"

class Sidebar(models.Model):
    title = models.CharField(max_length=200, verbose_name="عنوان")
    content = models.TextField(verbose_name="محتوا")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "نوار کناری"
        verbose_name_plural = "نوار کناری"

Yorth/home/models.py
from django.db.models.signals import post_save
from django.dispatch import receiver
import ghasedakpack
from django.db import models
from article.models import Article

class HomeBanner(models.Model):
    image = models.ImageField(upload_to="image/banner", verbose_name="تصویر", help_text="لطفاً تصویری با ابعاد ۱۹۲۰ در ۱۱۵۰ پیکسل وارد کنید")
    title = models.CharField(max_length=100, verbose_name="عنوان")
    text = models.TextField(verbose_name="متن")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "بنر صفحه اصلی"
        verbose_name_plural = "بنرهای صفحه اصلی"

class OurMissionImage(models.Model):
    image1 = models.ImageField(upload_to="image/mission", null=True, blank=True, help_text= "لطفاً تصویری با ابعاد 217 در 153 پیکسل وارد کنید", verbose_name= "تصویر ۱")
    image2 = models.ImageField(upload_to="image/mission", null=True, blank=True, help_text="لطفاً تصویری با ابعاد 271 در 191 پیکسل وارد کنید" , verbose_name="تصویر ۲")
    image3 = models.ImageField(upload_to="image/mission", null=True, blank=True, help_text="لطفاً تصویری با ابعاد 271 در 191 پیکسل وارد کنید" , verbose_name="تصویر ۳")
    image4 = models.ImageField(upload_to="image/mission", null=True, blank=True, help_text="لطفاً تصویری با ابعاد 339 در 236 پیکسل وارد کنید" , verbose_name="تصویر ۴")
    image5 = models.ImageField(upload_to="image/mission", null=True, blank=True, help_text="لطفاً تصویری با ابعاد 217 در 153 پیکسل وارد کنید",  verbose_name="تصویر ۵")
    image6 = models.ImageField(upload_to="image/mission", null=True, blank=True, help_text="لطفاً تصویری با ابعاد 179 در 126 پیکسل وارد کنید",  verbose_name="تصویر ۶")

    def __str__(self):
        return "تصاویر ماموریت ما"

    class Meta:
        verbose_name = "تصاویر ماموریت ما"
        verbose_name_plural = "تصاویر ماموریت ما"

class OurMission(models.Model):
    icon = models.FileField(upload_to='icon', verbose_name="ایکون(اختیاری)", blank=True, null=True,
                            help_text="فایل آیکون مرتبط با مأموریت خود را انتخاب کنید.")
    title = models.CharField(max_length=100, null=True, blank=True, verbose_name="عنوان")
    text = models.TextField(null=True, blank=True, verbose_name="متن")

    def __str__(self):
        return self.title if self.title else "بدون عنوان"

    class Meta:
        verbose_name = "ماموریت ما"
        verbose_name_plural = "ماموریت‌های ما"

class AricleList(models.Model):
    image = models.ImageField(upload_to="image/article", verbose_name="تصویر" ,help_text="لطفاً تصویری با ابعاد 396 در 372 پیکسل وارد کنید")
    title = models.CharField(max_length=100, verbose_name="عنوان")
    text = models.TextField(verbose_name="متن")
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="مقاله")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "لیست مقالات"
        verbose_name_plural = "لیست مقالات"


class SubscribeModel(models.Model):
    number = models.CharField(max_length=11, verbose_name="شماره تلفن")

    def __str__(self):
        return self.number

    class Meta:
        verbose_name = "عضویت در خبرنامه"
        verbose_name_plural = "عضویت‌ها در خبرنامه"


class Message(models.Model):
    message = models.TextField(
        verbose_name="پیام",
        help_text="پیامی که می‌خواهید به اعضای خبرنامه ارسال شود را وارد کنید."
    )

    def __str__(self):
        return f"پیام به اعضای خبرنامه: {self.message[:30]}"  # You can adjust the length as needed

    class Meta:
        verbose_name = "پیام به اعضای خبرنامه"
        verbose_name_plural = "پیام‌ها به اعضای خبرنامه"


@receiver(post_save, sender=Message)
def send_message_to_subscribers(sender, instance, created, **kwargs):
    if created:
        subscribers = SubscribeModel.objects.all()
        sms = ghasedakpack.Ghasedak("815fd62100f7a0e93271a74e3d418ec6818758cc8a4dbee1edf38a2868da0334")

        for subscriber in subscribers:

            response = sms.send({'message': instance.message, 'receptor': subscriber.number, 'linenumber': '10008566'})
            if response:
                print(f"Message successfully sent to {subscriber.number}")
            else:
                print(f"Failed to send the message to {subscriber.number}")

article/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Article(models.Model):
    title = models.CharField(max_length=200, verbose_name="عنوان")
    image = models.ImageField(upload_to="image/article", verbose_name="تصویر", help_text= "لطفاً تصویری با ابعاد 1921 در 966  پیکسل وارد کنید",)
    content = RichTextField(verbose_name="محتوا")
    public = models.DateField(verbose_name='تاربخ', auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"

class Sidebar(models.Model):
    title = models.CharField(max_length=200, verbose_name="عنوان")
    content = models.TextField(verbose_name="محتوا")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "نوار کناری"
        verbose_name_plural = "نوار کناری"

home/models.py
from django.db.models.signals import post_save
from django.dispatch import receiver
import ghasedakpack
from django.db import models
from article.models import Article

class HomeBanner(models.Model):
    image = models.ImageField(upload_to="image/banner", verbose_name="تصویر", help_text="لطفاً تصویری با ابعاد ۱۹۲۰ در ۱۱۵۰ پیکسل وارد کنید")
    title = models.CharField(max_length=100, verbose_name="عنوان")
    text = models.TextField(verbose_name="متن")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "بنر صفحه اصلی"
        verbose_name_plural = "بنرهای صفحه اصلی"

class OurMissionImage(models.Model):
    image1 = models.ImageField(upload_to="image/mission", null=True, blank=True, help_text= "لطفاً تصویری با ابعاد 217 در 153 پیکسل وارد کنید", verbose_name= "تصویر ۱")
    image2 = models.ImageField(upload_to="image/mission", null=True, blank=True, help_text="لطفاً تصویری با ابعاد 271 در 191 پیکسل وارد کنید" , verbose_name="تصویر ۲")
    image3 = models.ImageField(upload_to="image/mission", null=True, blank=True, help_text="لطفاً تصویری با ابعاد 271 در 191 پیکسل وارد کنید" , verbose_name="تصویر ۳")
    image4 = models.ImageField(upload_to="image/mission", null=True, blank=True, help_text="لطفاً تصویری با ابعاد 339 در 236 پیکسل وارد کنید" , verbose_name="تصویر ۴")
    image5 = models.ImageField(upload_to="image/mission", null=True, blank=True, help_text="لطفاً تصویری با ابعاد 217 در 153 پیکسل وارد کنید",  verbose_name="تصویر ۵")
    image6 = models.ImageField(upload_to="image/mission", null=True, blank=True, help_text="لطفاً تصویری با ابعاد 179 در 126 پیکسل وارد کنید",  verbose_name="تصویر ۶")

    def __str__(self):
        return "تصاویر ماموریت ما"

    class Meta:
        verbose_name = "تصاویر ماموریت ما"
        verbose_name_plural = "تصاویر ماموریت ما"

class OurMission(models.Model):
    icon = models.FileField(upload_to='icon', verbose_name="ایکون(اختیاری)", blank=True, null=True,
                            help_text="فایل آیکون مرتبط با مأموریت خود را انتخاب کنید.")
    title = models.CharField(max_length=100, null=True, blank=True, verbose_name="عنوان")
    text = models.TextField(null=True, blank=True, verbose_name="متن")

    def __str__(self):
        return self.title if self.title else "بدون عنوان"

    class Meta:
        verbose_name = "ماموریت ما"
        verbose_name_plural = "ماموریت‌های ما"

class AricleList(models.Model):
    image = models.ImageField(upload_to="image/article", verbose_name="تصویر" ,help_text="لطفاً تصویری با ابعاد 396 در 372 پیکسل وارد کنید")
    title = models.CharField(max_length=100, verbose_name="عنوان")
    text = models.TextField(verbose_name="متن")
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="مقاله")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "لیست مقالات"
        verbose_name_plural = "لیست مقالات"


class SubscribeModel(models.Model):
    number = models.CharField(max_length=11, verbose_name="شماره تلفن")

    def __str__(self):
        return self.number

    class Meta:
        verbose_name = "عضویت در خبرنامه"
        verbose_name_plural = "عضویت‌ها در خبرنامه"


class Message(models.Model):
    message = models.TextField(
        verbose_name="پیام",
        help_text="پیامی که می‌خواهید به اعضای خبرنامه ارسال شود را وارد کنید."
    )

    def __str__(self):
        return f"پیام به اعضای خبرنامه: {self.message[:30]}"  # You can adjust the length as needed

    class Meta:
        verbose_name = "پیام به اعضای خبرنامه"
        verbose_name_plural = "پیام‌ها به اعضای خبرنامه"


@receiver(post_save, sender=Message)
def send_message_to_subscribers(sender, instance, created, **kwargs):
    if created:
        subscribers = SubscribeModel.objects.all()
        sms = ghasedakpack.Ghasedak("815fd62100f7a0e93271a74e3d418ec6818758cc8a4dbee1edf38a2868da0334")

        for subscriber in subscribers:

            response = sms.send({'message': instance.message, 'receptor': subscriber.number, 'linenumber': '10008566'})
            if response:
                print(f"Message successfully sent to {subscriber.number}")
            else:
                print(f"Failed to send the message to {subscriber.number}")

Yorth/home/forms.py
from django import forms
from .models import SubscribeModel  # Make sure to import your model here

class SendMessageForm(forms.ModelForm):
    class Meta:
        model = SubscribeModel
        fields = []  # Add the appropriate fields if needed

home/forms.py
from django import forms
from .models import SubscribeModel  # Make sure to import your model here

class SendMessageForm(forms.ModelForm):
    class Meta:
        model = SubscribeModel
        fields = []  # Add the appropriate fields if needed

Yorth/article/views.py
from django.shortcuts import render
from . import models
from django.shortcuts import get_object_or_404


def article_view(request, id):
    article = get_object_or_404(models.Article, id=id)
    articles = models.Article.objects.all()
    sidebar = models.Sidebar.objects.all()
    print([article.id for article in articles])  # Debug print

    return render(request, "article/article.html", {
        "article": article,
        "articles": articles,
        "sidebar": sidebar
    })

Yorth/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import SubscribeModel,  HomeBanner, OurMission, OurMissionImage, AricleList
from article.models import Article
from itertools import zip_longest
import ghasedakpack


def home(request):
    banner = HomeBanner.objects.last()
    missionimage = OurMissionImage.objects.last()
    ourmission = OurMission.objects.all()

    if request.method == 'POST':
        number = request.POST.get('phone')
        try:
            SubscribeModel.objects.get(number=number)
        except SubscribeModel.DoesNotExist:
            if len(number) == 11 and number.isdigit():
                SubscribeModel.objects.create(number=number)

    return render(request, 'home/home.html', {
        'banner': banner,
        'mission': missionimage,
        'missions': ourmission,
    })



def send_messages_to_subscribers(message_text):
    subscribers = SubscribeModel.objects.al
    sms = ghasedakpack.Ghasedak("815fd62100f7a0e93271a74e3d418ec6818758cc8a4dbee1edf38a2868da0334")

    for subscriber in subscribers:
        response = sms.send({'message': message_text, 'receptor': subscriber.number, 'linenumber': '10008566'})

        if response:
            print(f"Message successfully sent to {subscriber.number}")
        else:
            print(f"Failed to send the message to {subscriber.number}")

article/views.py
from django.shortcuts import render
from . import models
from django.shortcuts import get_object_or_404


def article_view(request, id):
    article = get_object_or_404(models.Article, id=id)
    articles = models.Article.objects.all()
    sidebar = models.Sidebar.objects.all()
    print([article.id for article in articles])  # Debug print

    return render(request, "article/article.html", {
        "article": article,
        "articles": articles,
        "sidebar": sidebar
    })

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import SubscribeModel,  HomeBanner, OurMission, OurMissionImage, AricleList
from article.models import Article
from itertools import zip_longest
import ghasedakpack


def home(request):
    banner = HomeBanner.objects.last()
    missionimage = OurMissionImage.objects.last()
    ourmission = OurMission.objects.all()

    if request.method == 'POST':
        number = request.POST.get('phone')
        try:
            SubscribeModel.objects.get(number=number)
        except SubscribeModel.DoesNotExist:
            if len(number) == 11 and number.isdigit():
                SubscribeModel.objects.create(number=number)

    return render(request, 'home/home.html', {
        'banner': banner,
        'mission': missionimage,
        'missions': ourmission,
    })



def send_messages_to_subscribers(message_text):
    subscribers = SubscribeModel.objects.al
    sms = ghasedakpack.Ghasedak("815fd62100f7a0e93271a74e3d418ec6818758cc8a4dbee1edf38a2868da0334")

    for subscriber in subscribers:
        response = sms.send({'message': message_text, 'receptor': subscriber.number, 'linenumber': '10008566'})

        if response:
            print(f"Message successfully sent to {subscriber.number}")
        else:
            print(f"Failed to send the message to {subscriber.number}")

Yorth/home/templates/home/includes/article.html
{% load static %}
<section class="section section-lg bg-gray-1">
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-md-9 col-lg-7 wow-outer">
                <div class="wow slideInDown">
                    <h3>درباره دیابت</h3>
                    <p style="font-size: 20px">این بخش، مجموعه‌ای از مقالات مرتبط با دیابت را کاوش کنید. از اطلاعات مفید و به‌روز تا راهنمایی‌های عملی، مقالات ما به شما اطلاعاتی کامل در مورد دیابت ارائه می‌دهند</p>
                </div>
            </div>
        </div>
        <div class="row row-50 justify-content-center">
            {% for articlelist_item in articlelist %}
                <div class="col-md-6 col-lg-4 wow-outer">
                    <div class="wow fadeInUp">
                        <article class="box-causes">
                            <div class="box-causes-img" width="372" height="396">
                                <img src="{{ articlelist_item.image.url }}" alt=""
                                     style="background-size: contain; width:396px; height:280px"/>
                                <a class="button button-sm button-primary"
                                   href="{% url 'article:article' id=articlelist_item.article_id %}">ادامه مطلب</a>
                            </div>
                            <h4 class="font-weight-medium"><a
                                    href="{% url 'article:article' id=articlelist_item.article_id %}">{{ articlelist_item.title }}</a>
                            </h4>
                            <p class="">{{ articlelist_item.text }}</p>
                        </article>
                    </div>
                </div>
            {% endfor %}


        </div>
</section>

Yorth/home/templates/home/includes/banner.html
{% load static %}


<section class="section section-lg section-main-bunner section-main-bunner-filter">
  <div class="main-bunner-img" style="background-image: url({{banner.image.url}}); background-size: cover; background-position: center;"></div>
  <div class="main-bunner-inner">
    <div class="container">
      <div class="row row-50 justify-content-lg-center align-items-lg-center">
        <div class="col-lg-12">
          <div class="bunner-content-modern text-center">
            <h1 class="main-bunner-title">{{ banner.title }}</h1>
            <p style="font-size: 30px">{{ banner.text }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

Yorth/home/templates/home/includes/mission.html
{% load static %}


<section class="section section-xl" dir="rtl">
    <div class="container">
        <div class="row row-50 justify-content-lg-between align-items-lg-center">
            <div class="col-lg-6">
                <div class="box-img-animate">
                    <div class="box-img-animate-item"
                         data-parallax-scroll="{&quot;y&quot;: -20, &quot;x&quot;: -60,  &quot;smoothness&quot;: 50 }">
                        <img src="{{ mission.image1.url }}" alt="" style="height: 153px; width: 260px"></div>
                    <div class="box-img-animate-item"
                         data-parallax-scroll="{&quot;y&quot;: 150, &quot;x&quot;: 0,  &quot;smoothness&quot;: 50 }">
                        <img src="{{ mission.image2.url }}" alt="" style="height: 191px; width: 271px"></div>
                    <div class="box-img-animate-item"
                         data-parallax-scroll="{&quot;y&quot;:70, &quot;x&quot;: 250,  &quot;smoothness&quot;: 50 }">
                        <img src="{{ mission.image3.url }}" alt="" style="height: 191px; width: 271px"></div>
                    <div class="box-img-animate-item"
                         data-parallax-scroll="{&quot;y&quot;:30, &quot;x&quot;: 30,  &quot;smoothness&quot;: 50 }"><img
                        <img src="{{ mission.image4.url }}" alt="" style="height: 239px; width: 336px"></div>
                    <div class="box-img-animate-item"
                         data-parallax-scroll="{&quot;y&quot;:60, &quot;x&quot;: 70,  &quot;smoothness&quot;: 50 }"><img
                        <img src="{{ mission.image5.url }}" alt="" style="height: 126px; width: 179px"></div>
                    <div class="box-img-animate-item"
                         data-parallax-scroll="{&quot;y&quot;:0, &quot;x&quot;: -140,  &quot;smoothness&quot;: 50 }">

                        <img src="{{ mission.image6.url }}" alt="" style="height: 153px; width: 260px"></div>


                </div>
            </div>
            <div class="col-lg-6 col-xl-5">
                <div class="innset-xl-left-70" dir="rtl" style="text-align: right">
                    <h3>ماموریت ما</h3>
                    <p class="text-opacity-80" style="font-size: 20px">سازمان ما تعدادی از اهداف را که می‌توان به عنوان
                        ماموریت‌های ما شناخت،
                        دنبال می‌کند. بیشتر درباره آن‌ها می‌توانید در زیر بیاموزید.</p>
                    <div class="row row-50">
                        {% for mission in missions %}
                            <div class="col-md-6 col-lg-12">
                                <div class="box-icon-modern">
                                    {% if mission.icon %}
                                      <style>
                                        @media (max-width: 767px) {
                                            .img-mission {
                                                text-align: center;
                                                width: 7rem;
                                                margin-right: 11rem;
                                            }
                                        }
                                    </style>

                                     <img class="img-mission" src="{{ mission.icon.url }}" style="height: 80px;">
                                    {% else %}
                                        <div><span class="icon-xl linearicons-baby2 icon-primary"></span></div>
                                    {% endif %}
                                    <div class="box-icon-caption">
                                        <h4><a href="#">{{ mission.title }}</a></h4>
                                        <p style="font-size: 20px">{{ mission.text }}</p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Yorth/home/templates/home/includes/subscribe.html
{% load static %}


<section class="parallax-container bg-gray-600" data-parallax-img="{% static "images/1920_diabetesfinal.jpg" %}">
    <div class="parallax-content section-xxl text-center">
        <div class="container">
            <div class="row justify-content-md-center">
                <div class="col-md-9 col-lg-8 col-xl-8 wow-outer">
                    <div class="innset-xl-right-30 innset-xl-left-30">
                        <div class="wow slideInDown" dir="rtl">
                            <h3 dir="rtl" style="margin-bottom: 50px">اشتراک بگیرید تا مطلع شوید</h3>
                            <div class="message"></div>

                            <form class="rd-form rd-form-inline" id="subscription-form" style="margin-top: 0px">
                                {% csrf_token %}
                                <!-- Your form inputs here -->
                                <div class="form-wrap">
                                    <input class="form-input" id="phone" name="phone"
                                           style="text-align: center; font-size: 16px"
                                           placeholder="شماره تلفن را وارد کنید">
                                </div>
                                <div class="form-button">
                                    <button class="button button-primary button-lg" type="button"
                                            style="font-size: 14px"
                                            id="subscribe-btn">اشتراک‌گذاری
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
$(document).ready(function () {
    // Attach a click event handler to the subscribe button
    $("#subscribe-btn").click(function (event) {
        event.preventDefault(); // Prevent the default form submission behavior

        // Reset the message and input border
        $(".message").empty();
        $("#phone").removeClass("error-border");

        // Get the form data
        var formData = $("#subscription-form").serialize();

        // Validate the phone number (11 characters and numeric)
        var phoneNumber = $("#phone").val();
        if (phoneNumber.length !== 11 || !/^\d+$/.test(phoneNumber)) {
            // Display the error message
            $(".message").removeClass("success").addClass("error").html("لطفا یک شماره تلفن معتبر وارد کنید");

            // Add red border to the input field
            $("#phone").addClass("error-border");

            return; // Abort the submission
        }

        // Perform the AJAX POST request
        $.ajax({
            type: "POST",
            url: "{% url 'home:home' %}", // Replace 'your_subscription_endpoint' with the actual URL to handle the form submission on the server-side
            data: formData,
            success: function (response) {
                // Handle the successful response here (e.g., show a success message)
                console.log("Subscription successful!");
                $(".message").removeClass("error").addClass("success").html("اشتراک با موفقیت انجام شد");
            },
            error: function (xhr, status, error) {
                // Handle errors here (e.g., show an error message)
                console.error("Error occurred:", error);
                var errorMessage = xhr.responseText; // Get the error message from the server
                $(".message").removeClass("success").addClass("error").html(errorMessage);
            },
        });
    });
});
</script>